In [1]:
import numpy as np
import math 

Helper Function


In [2]:
class  helper :
    def __init__(self):
        self.id = 1
    def rotate_x( theta ):
        arr = np.array([
            [1 ,0 ,0 ],
            [0 ,math.cos(theta) , math.sin(theta)],
            [0 ,-math.sin(theta) , math.cos(theta)]
        ])
        return arr
    def rotate_y ( self , theta ):
        arr = np.array([
            [math.cos(theta) ,0 ,math.sin(theta) ],
            [0 , 1 , 0],
            [-math.sin(theta),0 , math.cos(theta)]
        ])
        return arr
    def rotate_z( self ,theta ):
        arr = np.array([
            [math.cos(theta) , -math.sin(theta), 0],
            [math.sin(theta) , math.cos(theta) ,0 ],
            [0,0,1]
        ])
        return arr
    
    def split_transform(self , T ):
        rotate = T[:3,:3]
        origin = T[:3, 3]
        return rotate , origin
    
    def build_transform(self ,rotate , origin ):
        T = np.pad(rotate, (0, 1), 'constant', constant_values=(0))
        T[0][3] ,T[1][3],T[2][3] = origin[0],origin[1],origin[2]
        T[3][3] = 1
        return T
                    
    def EularParameter_e4(R):
        e4 = 0.5*(1+ R[0,0] +R[1,1] +R[2,2] )** 0.5
    
        e1 = (R[3-1,2-1] - R[2-1,3-1])/(4*e4)
        e2 = (R[2-1,1-1] - R[1-1,2-1])/(4*e4)
        e3 = (R[1-1,3-1] - R[3-1,1-1])/(4*e4)
    
        return (e1,e2,e3,e4)
                    
        

Q1  A frame {B} and a frame {A} are initially coincident. Frame {B} is rotated about ˆ YB by
an angle , and then rotated about the new ˆ ZB by an angle . Determine the 3 × 3 rotation
matrix, A
BR, which will transform the coordinates of a position vector from BP, its value in
frame {B}, into AP, its value in frame {A}.

In [3]:
rot = helper()

In [4]:
theta = 30
theta = math.radians(theta) 
phi = 45
phi = math.radians(phi) 
def ques(theta,phi):
    ans1 = np.dot(rot.rotate_y(theta) , rot.rotate_z(phi) )
    return ans1

2. We are given a single frame {A} and a position vector AP described in this frame. We then
transform AP by first rotating it about ˆ ZA by an angle , then rotating about ˆ YA by an angle
. Determine the 3×3 rotation matrix operator, R(, ), which describes this transformation.

In [5]:
# theta = int(input("enter a angle in  degree "))
theta = 30
theta = math.radians(theta) 
# phi = int(input("enter a angle in  degree "))
phi = 45
phi = math.radians(phi) 
def ques(theta,phi):
    ans2 = np.dot(rot.rotate_z(theta) , rot.rotate_y(phi) )
    return ans2

Q3 (a) Given a transformation matrix:
BTA =

    [ 1    0            0             1   ]
    [ 0    cos(theta)   −sin(theta)   2   ]
    [ 0    sin(theta)   cos(theta)    3   ]
    [ 0    0            0             1   ]

Find ATB

In [6]:
theta = 30
theta = math.radians(theta)
def matrix(theta ):
    BTA = np.array([
    [ 1,    0,                 0,                  1   ],
    [ 0,    math.cos(theta),   -math.sin(theta),   2   ],
    [ 0,    math.sin(theta),   math.cos(theta),    3   ],
    [ 0,    0,                 0,                  1   ]
    ])
    return BTA

def ques3A( BTA ):
    
    rotate , origin = rot.split_transform(BTA)
#     print(rotate,origin)
#     new_rotate = np.linalg.inv(rotate)
    new_rotate = rotate.T
    new_origin = -1* np.dot( new_rotate , origin )
#     print(new_origin)
    ATB = rot.build_transform(new_rotate ,new_origin )
    return ATB
BTA = matrix(theta)   
print(ques3A(BTA))

[[ 1.          0.          0.         -1.        ]
 [ 0.          0.8660254   0.5        -3.23205081]
 [ 0.         -0.5         0.8660254  -1.59807621]
 [ 0.          0.          0.          1.        ]]


Q3 B Given theta = 45◦ and BP = [ 4 5 6 ].T 
 compute AP

In [7]:
theta = 45 
theta = math.radians(theta)
BP = np.array([ 4, 5, 6 ]).reshape(3,1)

def ques3B(theta ,BP):
    if np.shape(BP)[0] == 3 :
        l = list(BP.reshape(3,))
        l.append(1)
        BP = np.array(l).reshape(4,1)
    BTA = matrix(theta)
    ATB = ques3A(BTA )
    return np.dot( ATB , BP)

ques3B(theta,BP)
# print(ques3B(theta,BP))

array([[3.        ],
       [4.24264069],
       [0.        ],
       [1.        ]])

In [8]:
BP = np.array([ 4, 5, 6 ]).T
print(list(BP))

[4, 5, 6]


In [9]:
BTA[2][3]

3.0

In [10]:
BTA
np.pad(BTA, (0, 1), 'constant', constant_values=(0))

array([[ 1.       ,  0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.8660254, -0.5      ,  2.       ,  0.       ],
       [ 0.       ,  0.5      ,  0.8660254,  3.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ]])

Given the following 3 × 3 matrix: 

    R = [ 1/√2  0      1/√2 ]
        [ -1/2  1/√2   1/2  ]
        [-1/2   -1/√2  1/2  ] 
        
        
      Show that it is a rotation matrix.


In [11]:
def Ques4A(R):
    arr = np.dot(R,R.T)
    return (np.round(arr, 3) == np.identity(3, dtype = float)).all() 

In [12]:
R =  np.array([ [ 1/(2**0.5)  ,   0         ,  1/(2**0.5)   ] ,
                [ -1/2      ,   1/(2**0.5),  1/2       ],
                [-1/2       ,  -1/(2**0.5)  ,  1/2       ] ] )

In [13]:
print(Ques4A(R))

True


 Q4 B  What are the Euler parameters "1, "2, "3, "4 of R?


In [14]:
def ques4B(R):
    e4 = 0.5*(1+ R[0,0] +R[1,1] +R[2,2] )** 0.5
    
    e1 = (R[3-1,2-1] - R[2-1,3-1])/(4*e4)
    e2 = (R[2-1,1-1] - R[1-1,2-1])/(4*e4)
    e3 = (R[1-1,3-1] - R[3-1,1-1])/(4*e4)
    
    return (e1,e2,e3,e4)
    

In [15]:
ep = ques4B(R)
ep

(-0.35355339059327373,
 -0.14644660940672624,
 0.35355339059327373,
 0.8535533905932737)

Q 4 C Determine a unit vector that defines the axis of rotation and the angle (in degrees) of
rotation.

In [16]:
def ques4C (e1,e2,e3,e4):
    theta = 2* math.acos(e4)
    wx = e1/ math.sin(theta/2)
    wy = e2/ math.sin(theta/2)
    wz = e3/ math.sin(theta/2)
    vector = np.array( [ wx, wy, wz])
    return vector ,math.degrees(theta)

In [17]:
vector , theta = ques4C(ep[0],ep[1],ep[2],ep[3])
print(vector, theta)

[-0.67859834 -0.28108464  0.67859834] 62.799429619838094
